#include "thread.h"
#include <chrono>
#include <iostream>
#include <thread>
long long now_ms(){return std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
void set_camera_bridge_sample(bool face_detected,bool mouth_open,bool looking_forward,float mouth_x=0.5f,float mouth_y=0.5f,float confidence=0.9f,long long timestamp_ms=0){auto&s=runtime_state();s.camera_bridge.bridge_connected=true;s.camera_bridge.sample_ready=true;s.camera_bridge.face_detected=face_detected;s.camera_bridge.mouth_open_state=mouth_open;s.camera_bridge.looking_forward=looking_forward;s.camera_bridge.mouth_center_x=mouth_x;s.camera_bridge.mouth_center_y=mouth_y;s.camera_bridge.confidence=confidence;s.camera_bridge.timestamp_ms=timestamp_ms>0?timestamp_ms:now_ms();s.camera_bridge.backend="test-camera";}
void set_microphone_bridge_sample(bool voice_detected,float suggested_power,bool fallback_requested=false,float confidence=0.8f,long long timestamp_ms=0){auto&s=runtime_state();s.microphone_bridge.bridge_connected=true;s.microphone_bridge.sample_ready=true;s.microphone_bridge.voice_detected=voice_detected;s.microphone_bridge.fallback_requested=fallback_requested;s.microphone_bridge.suggested_power=suggested_power;s.microphone_bridge.confidence=confidence;s.microphone_bridge.timestamp_ms=timestamp_ms>0?timestamp_ms:now_ms();s.microphone_bridge.backend="test-microphone";}
void prepare(){reset_runtime();set_runtime_phase(RuntimePhase::READY);set_thread_mode(2);clear_task_queue(PriorityLevel::P2_FUNCTIONAL);clear_task_queue(PriorityLevel::P3_PARTICLE);submit_task(make_camera_task());submit_task(make_microphone_task());}
void restart_input(){clear_task_queue(PriorityLevel::P2_FUNCTIONAL);submit_task(make_camera_task());submit_task(make_microphone_task());render_data().ui.generate_task_status.clear();render_data().ui.particle_task_status.clear();}
long long next_timestamp_after(long long minimum_ms){ long long candidate = now_ms(); while(candidate <= minimum_ms){ std::this_thread::sleep_for(std::chrono::milliseconds(1)); candidate = now_ms(); } return candidate; }
void tick_until_no_particle_work(int max_ticks){for(int i=0;i<max_ticks;++i){if(scheduler_snapshot().p3_queue.empty() && current_render_data().ui.queued_particle_tasks==0) return; scheduler_tick();}}
int main(){prepare(); long long t=now_ms(); set_camera_bridge_sample(true,true,true,0.54f,0.45f,0.9f,t); set_microphone_bridge_sample(true,0.32f,false,0.8f,t); for(int i=0;i<6;++i){scheduler_tick(); if(current_render_data().ui.generate_task_status=="GENERATE created 3 particle tasks") break;} tick_until_no_particle_work(40); clear_task_queue(PriorityLevel::P2_FUNCTIONAL); submit_task(make_batch_particle_execution_task()); scheduler_tick(); std::cout<<"after cleanup statuses 0-5: "; for(int i=0;i<6;++i) std::cout<<current_render_data().particles[i].status<<","; std::cout<<" last_consumed="<<current_runtime_state().last_consumed_microphone_sample_ms<<"\n"; restart_input(); long long t2=next_timestamp_after(current_runtime_state().last_consumed_microphone_sample_ms); std::cout<<"t2="<<t2<<"\n"; set_camera_bridge_sample(true,true,true,0.53f,0.46f,0.9f,t2); set_microphone_bridge_sample(true,0.32f,false,0.8f,t2); for(int i=0;i<8;++i){scheduler_tick(); auto s=scheduler_snapshot(); std::cout<<"tick="<<s.frame_index<<" last_consumed="<<current_runtime_state().last_consumed_microphone_sample_ms<<" mic_ts="<<current_runtime_state().microphone_bridge.timestamp_ms<<" gen='"<<current_render_data().ui.generate_task_status<<"' p2="<<s.p2_queue.size()<<" p3="<<s.p3_queue.size()<<" q="<<current_render_data().ui.queued_particle_tasks<<" cam='"<<current_render_data().ui.camera_task_status<<"' mic='"<<current_render_data().ui.microphone_task_status<<"' status3="<<current_render_data().particles[3].status<<" status4="<<current_render_data().particles[4].status<<" status5="<<current_render_data().particles[5].status<<"\n"; }
}
